server:
  port: 9001

spring:
  application:
    name: quickstart-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: quickstart-gateway
          uri: lb://quickstart-provider
          predicates:
            - Path=/provider/**, /nacos/service/**